[2022-02-25 04:02:10,671] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Spotify_Song_dag.sheet_run scheduled__2022-02-25T04:01:29.363209+00:00 [queued]>
[2022-02-25 04:02:10,681] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Spotify_Song_dag.sheet_run scheduled__2022-02-25T04:01:29.363209+00:00 [queued]>
[2022-02-25 04:02:10,681] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-25 04:02:10,681] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-02-25 04:02:10,681] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-25 04:02:10,704] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): sheet_run> on 2022-02-25 04:01:29.363209+00:00
[2022-02-25 04:02:10,710] {standard_task_runner.py:52} INFO - Started process 12575 to run task
[2022-02-25 04:02:10,716] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Spotify_Song_dag', 'sheet_run', 'scheduled__2022-02-25T04:01:29.363209+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/spotify_check_dag.py', '--cfg-path', '/var/folders/nx/v6d0bskn22s742wqx2vwc_rm0000gn/T/tmpa62zj2bz', '--error-file', '/var/folders/nx/v6d0bskn22s742wqx2vwc_rm0000gn/T/tmpxw4wgn59']
[2022-02-25 04:02:10,719] {standard_task_runner.py:77} INFO - Job 111: Subtask sheet_run
[2022-02-25 04:02:10,776] {logging_mixin.py:109} INFO - Running <TaskInstance: Spotify_Song_dag.sheet_run scheduled__2022-02-25T04:01:29.363209+00:00 [running]> on host Anurags-MacBook-Pro.local
[2022-02-25 04:02:10,850] {logging_mixin.py:109} WARNING - /Users/user/oneplace/opVM/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py:510 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2022-02-25 04:02:10,858] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Spotify_Song_dag
AIRFLOW_CTX_TASK_ID=sheet_run
AIRFLOW_CTX_EXECUTION_DATE=2022-02-25T04:01:29.363209+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-25T04:01:29.363209+00:00
[2022-02-25 04:02:10,870] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/user/oneplace/dags/spotify_check_dag.py", line 128, in update_data_to_sheet
    data = cur.execute("select * from my_played_tracks").fetchall()
sqlite3.OperationalError: no such table: my_played_tracks
[2022-02-25 04:02:10,894] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Song_dag, task_id=sheet_run, execution_date=20220225T040129, start_date=20220225T040210, end_date=20220225T040210
[2022-02-25 04:02:10,910] {standard_task_runner.py:89} ERROR - Failed to execute job 111 for task sheet_run
Traceback (most recent call last):
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/user/oneplace/dags/spotify_check_dag.py", line 128, in update_data_to_sheet
    data = cur.execute("select * from my_played_tracks").fetchall()
sqlite3.OperationalError: no such table: my_played_tracks
[2022-02-25 04:02:10,954] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-25 04:02:10,983] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-25 04:02:10,989] {logging_mixin.py:109} WARNING - /Users/user/oneplace/opVM/lib/python3.9/site-packages/airflow/models/dag.py:1079 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
